### ISSUE TITLE
Is this project alive?

### ISSUE THREAD

**Issue by Temikus** [Netflix/Lipstick#117]
Considering that the master build fails and some other indicators of project being stale I wanted to ask whether this project is still being maintained.

**Comment by thedatachef** [comment]
@Temikus I was maintaining this project as part of my work at Netflix. Since moving on I'm not entirely sure what the status is. I've merged your pull request and fixed the failing build, but from there I'd say it's up in the air as I don't currently have the bandwidth to spend on this.

**Comment by charsmith** [comment]
I'm going to go ahead and close this.  We haven't been building new features on Lipstick, but the project is not dead.  Thanks @thedatachef for the fix for the build.
